services:
  crypto-square:
    container_name: crypto-square
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/crypto-square
    networks:
      - crypto-network

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - crypto-network

volumes:
  mongo-data:

networks:
  crypto-network:
    driver: bridge