name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  version: 1

jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variable
        run: |
          echo "version=${{ env.version }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
        
      - name: copy .env
        run: |
          echo '${{ secrets.PROD }}' >> ./.env
          echo 'version=${{ env.version }}' >> ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/front
          push: true
          tags: ghcr.io/atmo-hdf/hermes-front-prod:${{ env.version }}

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   environment: 
  #     name: production
  #     url: https://csquare.dev
  #   needs: [build-prod]
  #   steps:

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.REGISTRY_TOKEN }}
